version: "3"

services:
  postgresdb:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hacker_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    env_file:
      - .env
    networks:
      - public

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
#    container_name: elasticsearch_container
#    restart: unless-stopped
#    ports:
#      - "9300:9300"
#    environment:
#      - cluster.name=docker-cluster
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS: -Xms2048m -Xmx2048m"
#    env_file:
#      - .env
#    volumes:
#      - elasticsearch_volume:/usr/share/elasticsearch/data

  app:
    image: spring-boot-app
    container_name: spring_container
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
#      - elasticsearch
    networks:
      - public

volumes:
  postgres_volume:
  elasticsearch_volume:
    driver: local

networks:
  public:
    driver: bridge